name = "kivo-main"
compatibility_date = "2024-01-01"

main = "backend/src/index.js"

[[d1_databases]]
binding = "DB"
database_name = "kivo-db"
database_id = "99169367-d104-48ad-ab07-612185e7bb8d"
